spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022212829?createDatabaseIfNotExist=true'
    username: 2022212829
    password: 2022212829
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always
#      自动读取生成数据表

logging:
  level:
    sql: debug
    org:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'