#自动读取生成数据表
spring:
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    sql: debug
    org:
      example: debug
    root: warn
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'



#自定义密钥
my:
  secretkey: OIioun9