spring:
  data:
    redis:
      host: 120.46.159.231
      port: 6379
      username: default
      password: 2046
      database: 15

logging:
  level:
    sql: debug
    org:
      example: debug
    root: warn
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

